### ISSUE TITLE
[feat req] flake lock file update tool

### ISSUE THREAD

**Issue by RingOfStorms** [viperML/nh#105]
I have no idea if this is in scope for what you want in NH. But I would like some nix flake commands. Right now my main one would be a wrapper around updating flake lock files. Particuarily seeing all the inputs and easily updating just one of them:
https://discourse.nixos.org/t/how-to-update-a-single-flake-input/13584

Something along the lines of `nh flake update` which then prompts you with several options:
* Not a TUI could just be a numbered list: `Press # to make a selection`
    1. Update all
    2. Update "nixpkgs" input
    3. Update "flake-utils" input
    ...
* A TUI could be a bit more sophisticated looking version of the above

A bonus feature of the above could be displaying the current version mismatch (like current version -> latest version) next to each option.

And a stretch goal, `nh` could be used to provide Linter diagnostics for a flake lock file using the same code, and therefore be run with something like https://github.com/mfussenegger/nvim-lint to produce editor virtual text like https://github.com/Saecki/crates.nvim

**Comment by viperML** [comment]
Thank you, I will consider it
