### ISSUE TITLE
`nh update` to update flake inputs

### ISSUE THREAD

**Issue by Infinidoge** [viperML/nh#106]
Having written [my own little CLI helper](https://github.com/Infinidoge/universe-cli/), `nh` looks really nice! Plus, it re-implements the management commands in cases where it can be done better, instead of just wrapping them. Well done!

`nh update` would run `nix flake update` on `FLAKE` to update its inputs, accepting arguments to specify the specific inputs to update as necessary.

**Comment by ToyVo** [comment]
For what is worth nh os switch -u will update the flake inputs
