### ISSUE TITLE
nh exits with error after building

### ISSUE THREAD

**Issue by unixpariah** [viperML/nh#111]
Running 'nh os switch' properly builds derivation paths and then exits with this error:

```bash
> Activating configuration
Error:
   0: Activating configuration
   1: No such file or directory (os error 2)
   2: No such file or directory (os error 2)

Location:
   src/commands.rs:57
```

running regular nixos-rebuild switch command right after instantaniously updates system

**Comment by viperML** [comment]
rerun with --verbose please

**Comment by viperML** [comment]
nh uses sudo

**Comment by unixpariah** [comment]
Works after enabling sudo instead of doas, thanks for help.
