### ISSUE TITLE
nh is sexy AF 

### ISSUE THREAD

**Issue by cig0** [viperML/nh#113]
![image](https://github.com/viperML/nh/assets/394089/61b60fb5-8eca-452b-9199-3e9a3e1661dc)

**Comment by cig0** [comment]
I just wanted to stop by to say that :raised_hands:

**Comment by viperML** [comment]
90% of that screenshot is occupied by the output of nvd

**Comment by cig0** [comment]
I didn't know about that project, but it's pretty cool. I'm still learning the ropes around NixOS :ok_hand:
