### ISSUE TITLE
Notification when is needed to give password

### ISSUE THREAD

**Issue by sorathpanzer** [viperML/nh#115]
One small issue i have is, the switch and update args get some time until we have to give the password,
would be nice to have dunst (and similar) notification systems, when is needed to give the password.
Sometimes i'm doing other stuff, and i find myself always changing workspace to see if is asking for the password.
Another alternative, is to give the password at the beginning.
Keep up the good working, nh makes NixOS switch/update smoother. Thanks

**Comment by viperML** [comment]
Will be done in #107
