### ISSUE TITLE
Implement a option to not clean development flakes / specific flake or shell configs.

### ISSUE THREAD

**Issue by jasper-at-windswept** [viperML/nh#116]
It is quite frustrating everytime I run `nh clean all` just to clean my system and it deletes all of my development flakes.

Can an option please be added to not clean specific flakes or flakes that are not part of the system configuration?

**Comment by viperML** [comment]
use --keep-since

**Comment by jasper-at-windswept** [comment]
> use --keep-since

Oh I just found that now thank you, but it says based of a time period, could you explain what that time period is and what it means?

**Comment by jasper-at-windswept** [comment]
I mostly understood what to put into there but how does that correlate to keeping development flakes intact?

**Comment by devurandom** [comment]
I believe I am suffering from a similar issue. direnvs are removed entirely. I would like a behaviour as I get for home manager: The latest generation should be kept and only older generations should be removed. `nh clean all` outputs that it will keep 1 generation, but for direnvs it deletes everything. How can I change that?
