### ISSUE TITLE
Error activating system configration

### ISSUE THREAD

**Issue by thom-cameron** [viperML/nh#117]
Hi there. I just updated to nixos 24.05 and therefore have access to nh. It's cool, thanks for making it. 

When trying to switch to a new system configuration using nh, I get an error though: 

```
thom@nix-lat:~
> nh os switch -v                                                                                         
TRACE nh::logging:86: Logging OK
DEBUG nh:21: args=NHParser { verbose: true, command: Os(OsArgs { action: Switch(OsRebuildArgs { common: CommonRebuildArgs { dry: false, ask: false, flakeref: FlakeRef("/home/thom/.config/nixos"), update: false, no_nom: false, diff_provider: "nvd diff" }, hostname: None, specialisation: None, no_specialisation: false, extra_args: [] }) }) }
DEBUG nh::nixos:42: out_dir: TempDir { path: "/tmp/nh-os-iVxsvr" }
DEBUG nh::nixos:43: out_link "/tmp/nh-os-iVxsvr/result"
> Building NixOS configuration
DEBUG nh::commands:136: cmd=Pipeline { nix build '/home/thom/.config/nixos#nixosConfigurations."nix-lat".config.system.build.toplevel' --log-format internal-json --verbose --out-link /tmp/nh-os-iVxsvr/result | nom --json }
Finished at 11:16:43 after 0s
DEBUG nh::nixos:96: target_specialisation: None
> Comparing changes
DEBUG nh::commands:53: cmd=Exec { nvd diff /run/current-system /tmp/nh-os-iVxsvr/result }
<<< /run/current-system
>>> /tmp/nh-os-iVxsvr/result
No version or selection state changes.
Closure size: 1806 -> 1806 (0 paths added, 0 paths removed, delta +0, disk usage +0B).
> Activating configuration
DEBUG nh::commands:53: cmd=Exec { sudo /tmp/nh-os-iVxsvr/result/bin/switch-to-configuration test }
Error: 
   0: Activating configuration
   1: Exec format error (os error 8)
   2: Exec format error (os error 8)

Location:
   src/commands.rs:57
```

I think everything is configured fine on my end as `nh home switch` is working fine for me. 

I wonder if it's an issue with permissions as I have replaced sudo with doas (with a symlink). This would be a bit strange though as `nh clean all` prompts me for my password and cleans up successfully.

**Comment by viperML** [comment]
No idea what the issue could be. Have you tried to run `sudo /tmp/nh-os-iVxsvr/result/bin/switch-to-configuration test` on your regular terminal?

**Comment by thom-cameron** [comment]
Just tried that but nh doesn't appear to have written the "nh-os-iVxsvr" folder it says it has. I just get a "command not found" as a result.

It also seems to be able to create "nh-home-*" folders, just not os ones.

**Comment by viperML** [comment]
For any `os` command, it doesn't create any `/tmp/nh-os-*` folder?

**Comment by thom-cameron** [comment]
Nope. Here's an example:

```
thom@nix-lat:~
> ls /tmp/ | rg ^nh                                                                                        
nh-home-eDPDz5

thom@nix-lat:~
> nh os build                                                                                             
> Building NixOS configuration
warning: Git tree '/home/thom/.config/nixos' is dirty
Finished at 12:03:32 after 9s
> Comparing changes
<<< /run/current-system
>>> /tmp/nh-os-QYAV08/result
No version or selection state changes.
Closure size: 1806 -> 1806 (0 paths added, 0 paths removed, delta +0, disk usage +0B).

thom@nix-lat:~
> ls /tmp/ | rg ^nh                                                                                       
nh-home-eDPDz5
```

I'm on nixos/home-manager version 24.05 and nix version 2.18.2.

**Comment by viperML** [comment]
And if you run the nix build command manually?

```
mkdir -p /tmp/nh-os-iVxsvr

nix build '/home/thom/.config/nixos#nixosConfigurations."nix-lat".config.system.build.toplevel' --out-link /tmp/nh-os-iVxsvr/result
```

**Comment by thom-cameron** [comment]
After creating the directory with doas mkdir, here's what I get:

```
nix build '/home/thom/.config/nixos#nixosConfigurations."nix-lat".config.system.build.toplevel' --out-link /tmp/nh-os-iVxsvr/result
warning: Git tree '/home/thom/.config/nixos' is dirty
error: creating symlink from '/tmp/nh-os-iVxsvr/result.tmp-244084-1335243724' to '/nix/store/1jhdl46wy34q866lb3vhr207pbwh7lbi-nixos-system-nix-lat-24.05.20240524.d12251e': Permission denied
```

**Comment by viperML** [comment]
The directory must be created by your user, and you should be able to do so from the permissions of `/tmp`:
```
$ stat --format="%a" /tmp
1777
```

**Comment by viperML** [comment]
Then I have no idea why nix doesn't create the symlink if ran within nh

**Comment by viperML** [comment]
Ah right, I just remember I use the crate `tempfile` for the outlink, which is cleared after nh exits, with errors or not.

> I have the impression, that nh disregards the symlink of sudo to doas and always tries to execute sudo directly.
That's handled by the crate subprocess, which I should probably replace with std::process

**Comment by viperML** [comment]
Could you run with --verbose and paste the output?

**Comment by viperML** [comment]
And you have sudo?

**Comment by viperML** [comment]
> removing obsolete file ‘/etc/sudoers’...

Please use `<whatever> nh os rebuild -R` if you plan to remove sudo.

**Comment by viperML** [comment]
> I want to use nh with doas just like with sudo.

You will have to wait for #107 then
