### ISSUE TITLE
Support [an equivalent of] `home-manager build`

### ISSUE THREAD

**Issue by miniBill** [viperML/nh#118]
Next to `switch`, it would be nice to have a `build` command

**Comment by viperML** [comment]
Sounds easy to implement, I'll let you go ahead if you want

**Comment by miniBill** [comment]
It seems you have already done it, it just hasn't reached nixpkgs stable yet!

**Comment by DerRockWolf** [comment]
There is the `nh home build` command but it doesn't create a `result` symlink to the build result.
Is this intended?
