### ISSUE TITLE
nh.flake must be a directory, not a nix file

### ISSUE THREAD

**Issue by tobias-kuendig** [viperML/nh#120]
My Nix flake is stored in `/home/user/.nix`. Using the following config:

```nix
   programs.nh = {
     enable = true;
     flake = "/home/user/.nix";
   };
```

I get the following error:

```
nh.flake must be a directory, not a nix file
```

It looks like the assertion of the Nix module is too broad and does not actually check if the path is a directory or a file:

https://github.com/NixOS/nixpkgs/blob/66ded85976f2d9522455596aeef5b457c6b1ca70/nixos/modules/programs/nh.nix#L68

Using `lib.pathType` would probably be more stable?

https://github.com/NixOS/nixpkgs/blob/66ded85976f2d9522455596aeef5b457c6b1ca70/lib/filesystem.nix#L46

**Comment by viperML** [comment]
You can use sessionVariables directly to skip the check
