### ISSUE TITLE
Collect warnings of the nix build

### ISSUE THREAD

**Issue by becknik** [viperML/nh#122]
Hey,

when building my nix config on slow machine recently, I discovered some Nix-specific warnings for the build about a upstream deprecation of some options. I also built this config a couple of times on my faster main main machine and never discovered those warnings.
And since I really enjoy the "error section" of nh (which could be a bit longer in my opinion), I thought about a second section of nh to collect all the warnings of the nix build and display them after the build is finished.

What do you think of this? Is this feature even possible to implement?

**Comment by viperML** [comment]
Duplicare #64 

Nom issue, you can use `--no-nom`
