### ISSUE TITLE
Networking stats

### ISSUE THREAD

**Issue by leon-erd** [viperML/nh#123]
The one thing I'm missing from `nh` is networking stats (total MB to download, how much already has been downloaded, current download speed). That is really useful in the default `nixos-rebuild switch` command because for me that's a better estimate on the progress of the command. Didn't find the option anywhere.

**Comment by viperML** [comment]
nh doesn't show anything, what you see is the output of nix-output-monitor.
You can toggle nom with --no-nom

**Comment by zyansheep** [comment]
https://github.com/maralorn/nix-output-monitor/issues/4 is the issue to track for anyone interested.

**Comment by koiuo** [comment]
It looks like nom has implemented some support for network statistics, but I don't see anything in nh. I also could not find any mentions of that in the documentation

**Comment by leon-erd** [comment]
You can overlay nom in your nixpkgs with a version that does have the stats. Then you will also see them with nh :)

**Comment by NotAShelf** [comment]
Since NOM is not a library, it's not up to me which version of it is used alongside NH. I intend to rewrite it as a Rust library eventually, so that we can stop shelling out.

For now using an overlay is feasible as @leon-erd has mentioned.
