### ISSUE TITLE
Add clap_complete_nushell

### ISSUE THREAD

**Issue by BurntKrispe** [viperML/nh#124]
I recently picked up nushell as my primary shell. I realized nh doesn't support it yet and when using carapace-bridge for completions, it returns 'error: unrecognized subcommand 'complete'` as it seems completions requires the crate feature "unstable-dynamic" and the use of the module 'clap_complete::dynamic'.

I'm not sure which method would be preferred or if there's another one I'm not aware of.

**Comment by viperML** [comment]
Could you give an example of any package in nixpkgs that installs nushell completions?

**Comment by BurntKrispe** [comment]
> Could you give an example of any package in nixpkgs that installs nushell completions?

There are some in the repo:

https://github.com/clap-rs/clap/blob/master/clap_complete_nushell/examples/nushell_completion.rs

**Comment by viperML** [comment]
In nixpkgs, nix code

**Comment by BurntKrispe** [comment]
I'm not sure, but when I get my system set up I can look into making a pr for this change. Though at this rate I'm considering using fish as it seems to have a larger community supporting it in general.

**Comment by viperML** [comment]
I'm pretty sure packages (nh) can't install their own completions to nushell. In the other shells, this is done by putting files in $out/share :

```
$ eza --tree result/share/
result/share
├── bash-completion
│  └── completions
│     └── nh.bash
├── fish
│  └── vendor_completions.d
│     └── nh.fish
└── zsh
   └── site-functions
      └── nh
```

https://github.com/viperML/nh/blob/0d76479fcdec0243ea560d1e2fde854337787e3a/package.nix#L44-L51
