### ISSUE TITLE
Add option for default search channel 

### ISSUE THREAD

**Issue by Diomeh** [viperML/nh#126]
Although the `--channel` parameter is there, I think it would be useful to have a declarative way to specify the channel when searching packages, like so:

```nix
programs.nh.search.channel = "nixos-24.01";
```

In my case I'm not the unstable channel so for every search I need to explicitly specify it every time.

**Comment by viperML** [comment]
I don't think that's a good solution. If anything nh could detect which channel you are on. Because AFAIK we can't query elasticsearch for a specific commit

**Comment by Diomeh** [comment]
I'm not aware of the internals of `nh` but if a declarative option isn't possible then I'd think an intuitive default would be the channel in which the system is on instead of `nixos-unstable`.

**Comment by viperML** [comment]
Yeah, but I don't know how to do that

**Comment by viperML** [comment]
Fixed in https://github.com/viperML/nh/commit/6fb30a4d490a98d08628ed93a90a9d23820ef9c8
