### ISSUE TITLE
Behaviour under `.gitignore` presence

### ISSUE THREAD

**Issue by heshdotcc** [viperML/nh#127]
Is there a way to, given a repository, make `nh` work regardless of `.gitignore` rules?

I have a directory where `nh` works well, but if I set up a repository with `.gitignore` rules, then it throws:

`No such file or directory`

When trying to evaluate things I've git-ignored but definitively are there, is there a way to bypass such behavior?

Thanks in advance for any suggestions!

**Comment by viperML** [comment]
Nh doesn't see any gitignore, as it's just a wrapper around nix itself.
