### ISSUE TITLE
Support for flakegen

### ISSUE THREAD

**Issue by xtrm-en** [viperML/nh#128]
This is very much a random idea, but I came across the [flakegen](https://github.com/jorsn/flakegen) project that aims to allow for templating the `flake.nix` file (from something like a `flake.in.nix` or `flake.template.nix` file) to allow for the full set of the Nix language to be used when declaring your flake.

It would be interesting to see `nh` detect and support these files and regenerate the flake file if a template is detected.

**Comment by RGBCube** [comment]
Nix is already turing complete and super flexible, allowing you to compose almost anything. This seems really out of scope for this project & kind of pointless

**Comment by xtrm-en** [comment]
This might definitely be out of scope, yes, but worth a try in my book :)

That being said, flakes being written in a subset of the Nix language (see https://github.com/NixOS/nix/issues/4945 or [flakegen's readme](https://github.com/jorsn/flakegen?tab=readme-ov-file#flakegen)) justify the existence of such a project, so I wouldn't really call it pointless.

**Comment by RGBCube** [comment]
> This might definitely be out of scope, yes, but worth a try in my book :)
> 
> That being said, flakes being written in a subset of the Nix language (see [NixOS/nix#4945](https://github.com/NixOS/nix/issues/4945) or [flakegen's readme](https://github.com/jorsn/flakegen?tab=readme-ov-file#flakegen)) justify the existence of such a project, so I wouldn't really call it pointless (or did you mean pointless in the context of this project? might be misinterpreting here)

The latter, yes, I can see it being useful to fix the mess that flakes are, but it's up to @viperML to accept this feature

**Comment by viperML** [comment]
I only add features to nh that I use myself, and I don't use templates
