### ISSUE TITLE
[Feature Request] Add option to suppress build output

### ISSUE THREAD

**Issue by Schweber** [viperML/nh#129]
I'm just starting to use flakes but it is my understanding that `nixos-rebuild` doesn't allow the option `--no-build-output` when building a flake.

I'm annoyed by the build output though (i only care about errors and not about e.g. the 400+ lines of build output for the frequent compilations of `xwayland` every time it gets updated) and am wondering if `nh` could be made to filter out the build output as an option.

**Comment by viperML** [comment]
`nh os switch --no-nom`

**Comment by viperML** [comment]
You should open an issue in the repo of nom then, not here
