### ISSUE TITLE
Use nix-fast-build

### ISSUE THREAD

**Issue by diniamo** [viperML/nh#132]
I think it would be fitting to use [nix-fast-build](https://github.com/Mic92/nix-fast-build) for faster build times in nh.

**Comment by viperML** [comment]
I just tried nfb and it crashed my system with OOM

![image](https://github.com/viperML/nh/assets/11395853/8cd0d59a-e623-4c1c-be44-2d7495dbfac1)

**Comment by diniamo** [comment]
wow, okay
