### ISSUE TITLE
Add flag to enable creation of `result` symlinks for build commands

### ISSUE THREAD

**Issue by DerRockWolf** [viperML/nh#133]
On the one hand, it's really nice that `nh * build` doesn't create `result` symlinks, as they (if not cleaned up) prevent garbage collection,
on the other hand it's sometimes really helpful to be able to look around the files that will end up on my system.

Therefore, I would suggest adding a new flag (e.g., `--symlink-result`) to the `nh os build` & `nh home build` commands that creates the `result` symlink.

If you agree that this would be a good feature for `nh` I can also try to implement it 🙂

**Comment by viperML** [comment]
The current implementation unconditionally sets the out-link into some `::tempfile` here: https://github.com/viperML/nh/blob/7f8a1859ed6ea971fcf49b07ca8938e3000c3af4/src/nixos.rs#L39-L41

If you want to implement it, check if `matches!(rebuild_type, OsRebuildType::Build(_)`, and change that path to `result`

**Comment by DerRockWolf** [comment]
closed by 6878bc368e03915680dc1cfc929dc825bf5b7ca1

**Comment by Parsifa1** [comment]
is seems that if i use `nh darwin switch` in any folder, it will create a @result in it :(
