### ISSUE TITLE
How to use "--build-host"

### ISSUE THREAD

**Issue by pbek** [viperML/nh#134]
Thank you for this amazing tool!

Is there a way to use `--build-host` as additional argument?

When I do a `nh os build -H myhost . -- --build-host user@host` I get:

```
> Building NixOS configuration
error: unrecognised flag '--build-host'
┏━ 1 Errors: 
┃ error: unrecognised flag '--build-host'
┣━━━                                                            
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 09:37:58 after 0s
Error: 
   0: Command exited with status Exited(1)
```

**Comment by viperML** [comment]
`--build-host` is a feature of `nixos-rebuild`, not of `nix build`. It is simply not implemented in `nh`

**Comment by pbek** [comment]
Ah, thank you very much for clearing that up!

**Comment by viperML** [comment]
Ideally this would be implemented in https://github.com/viperML/nh/pull/107 , but I haven't had the time for it

**Comment by pbek** [comment]
Then I hope for some rainy or cold days! 😆 I really like all the extra information that nh shows me! 😉
