### ISSUE TITLE
[nixpkgs] nh.flake incorrectly identifying `.nix` folder as a nix file

### ISSUE THREAD

**Issue by atagen** [viperML/nh#136]
My flakes are in ~/.nix, which appears to fail one of the nix package's assertions.

**Comment by viperML** [comment]
I don't want to remove that check, so all I can tell you is to use a different folder.

**Comment by atagen** [comment]
looking at the module, would [lib.pathIsDir](https://noogle.dev/f/lib/pathIsDirectory) work [here](https://github.com/NixOS/nixpkgs/blob/4f2a4548d1c48a333658239f97d5deb1069f94ff/nixos/modules/programs/nh.nix#L68)?

**Comment by viperML** [comment]
No,that would be impure

**Comment by atagen** [comment]
I guess I can fix it for myself locally, but as a last ditch: what if the assertion checked for `ending != /.nix && ending == .nix`?

**Comment by viperML** [comment]
In linux, the path, filename or extensions doesn't carry any information about a file being regular or a folder.

**Comment by atagen** [comment]
that seems to be the root cause of the issue, yes. thanks anyway
