### ISSUE TITLE
[Feature] Support nix-darwin as `darwinConfigurations` // plain hostname infer for HM configs on MacOS

### ISSUE THREAD

**Issue by ppenguin** [viperML/nh#139]
I recently started using my MBP again with `nix`(I had an elaborate system and HM config for it in my multi-flake from before I started using `nh`) and noticed that I had named the system configs returned by `nix-darwin`'s `lib.darwinSystem` under the flake's output attribute `darwinConfigurations`. 

I think at the time there was an issue with some of my flake logic that warranted to not have darwin system configs under `nixosConfigurations`, and since they're technically not the same it might make sense to keep them separated?

In that case it would be cool if `nh` would check for `darwinConfigurations.$(hostname -s)` when run on a darwin system?

For HM configs the required change to make it work seems to be trivial: it appears the automatically inferred hostname on Mac is `<hostname>.local` (i.e. the output of `hostname`),  it would work if `nh` makes sure to only get the plain hostname (i.e. the output of `hostname -s`)

**Comment by bestlem** [comment]
The author @viperML does not have access to any macs and so can't support this see https://github.com/viperML/nh/issues/67 & https://github.com/viperML/nh/pull/97

There is a fork nh_darwin https://github.com/ToyVo/nh_darwin which I think meets your requirements.

**Comment by ppenguin** [comment]
@bestlem Hey thanks! Seems I didn't search closely enough through previous issues. I'll take a look (probably use the fork, possibly with an overlay only on darwin...)

**Comment by nikhilmaddirala** [comment]
Any chance we can revisit this issue instead of using the fork?

With darwin-rebuild I can do: `sudo darwin-rebuild switch --flake .#mymac`

But with nh I can't do: `nh darwin switch .#mymac`

Instead I have to do: `nh darwin switch .#darwinConfigurations.mymac`

**Comment by NotAShelf** [comment]
I would appreciate an incoming PR (or a Macbook delivered to my home address :p) for this matter. Without a Darwin machine, I am not entirely positive I can reliably support Darwin-specific changes myself, but I am happy to review a PR.
