### ISSUE TITLE
feature request: commit to git after `nh os switch -u <flake>`

### ISSUE THREAD

**Issue by kacperwyczawski** [viperML/nh#143]
It would be nice if one could run `nh os switch -u <flake> -c` (or `--commit`) to commit changes to git repository.

Commit message could look like this:
```
update: generation 42 -> 43

updated packages:
<...>
added packages:
<...>
removed packages:
<...>
```

**Comment by XBagon** [comment]
Could you briefly explain what

> could not make room for extra args

means?
Are you talking about having `--` as a arg separator and multiple separators could conflict with the internal commands?

Would something like allowing hooks for events like successful switch, be a valid workaround?
Also then git specific things would not need to be implemented and in theory we could have better/more specialized hooks than `system.activationScripts` (which would not only trigger when using switch).
