### ISSUE TITLE
feature request: option to set shell script to determine flakeref

### ISSUE THREAD

**Issue by Libadoxon** [viperML/nh#145]
I would wish for an option to set a shell script in the `NixOs` module which gets run on rebuild to determine the right flakeref to use. For people who wish for a different way to distinguish their hosts other than hostname. I would be willing to try to implement such a feature if the general idea would be welcomed.

**Comment by viperML** [comment]
You can write a wrapper script that exports the proper $FLAKE env variable or calls nh with the proper arguments.
