### ISSUE TITLE
Add option/flag that shows if an update for the inputs is available

### ISSUE THREAD

**Issue by Schweber** [viperML/nh#147]
This is similar to #105 but simpler: I would like to have an option/flag that makes `nh` check if updates for the inputs are available and report via text and exit code. The updates shouldn't be downloaded or applied in any way.

This way, i could run this command e.g. once a day as a systemd Unit and receive a notification when updates are available so that i can run e.g. `nh os switch -u` manually to update my system.

**Comment by viperML** [comment]
I don't want that in NH.
