### ISSUE TITLE
```nh clean all``` clears nix-direnv caches 

### ISSUE THREAD

**Issue by sachinchaudhary1808** [viperML/nh#152]
is the title true ? or it's a bug ?

**Comment by viperML** [comment]
It is intentional. You can adjust the age of the direnv gcroots.

**Comment by sachinchaudhary1808** [comment]
> It is intentional. You can adjust the age of the direnv gcroots.

Can u explain more ?    I don't get what u mean i don't know much stufd

**Comment by devurandom** [comment]
I believe I have a similar problem. `nh clean all` removes direnvs entirely. I would like to get the same behaviour for direnvs as I get for home manager: The latest generation should be kept, older generations should be cleaned. How can I achieve that?
