### ISSUE TITLE
`nh home switch flakepath/#user@host` is not a valid URL

### ISSUE THREAD

**Issue by carschandler** [viperML/nh#157]
My MacBook reset its hostname in a new software update so I had to use the syntax

`nh home switch .#chan@mbp` where my flake hm configuration is defined like

```nix
      homeConfigurations = {
        "chan@mbp" = home-manager.lib.homeManagerConfiguration {
          ...
```

And I got this error:

```
nh home switch .#chan@mbp
error: '.#mbp#homeConfigurations' is not a valid URL
Error:
   0: Failed to parse nix-eval output:

Location:
   src/home.rs:204
```

But was able to build with `home-manager switch --flake .chan@mbp` as normal.

**Comment by carschandler** [comment]
Nooooooooooooo

Caught red-handed

Thanks. I may open a PR to suggest that option in the error message if that's cool.

**Comment by ToyVo** [comment]
If your issue was .local being part of the hostname that has been fixed on nh-darwin to account for that
