### ISSUE TITLE
<FLAKEREF> required despite setting flake location in config

### ISSUE THREAD

**Issue by ferife** [viperML/nh#164]
Whenever I try to run `nh os switch`, I get the following error
```
error: the following required arguments were not provided:
  <FLAKEREF>

Usage: nh os switch <FLAKEREF> [-- <EXTRA_ARGS>...]

For more information, try '--help'.
```
This is despite the fact that I've already set the flake in my configuration.

The only way the command will work is if I type out the path to my config as part of the terminal command. (AKA `nh os switch path/to/my/flake`)

I've tried setting the path to the flake in all three following ways, all resulting in the error above

```
programs.nh = {
  enable = true;
  flake = "path/to/my/flake";
};
```

```
programs.nh.enable = true;
environment.sessionVariables.FLAKE = "path/to/my/flake";
```

```
environment.systemPackages = with pkgs; [ nh ];
environment.sessionVariables.FLAKE = "path/to/my/flake";
```

**Comment by viperML** [comment]
Reboot and post the output of `printenv FLAKE`

**Comment by ferife** [comment]
Yeah, that worked. Can't believe that I failed to figure out the classic "turn it off and on" on my own lol
