### ISSUE TITLE
nh os switch /etc/nixos#default doesn't work

### ISSUE THREAD

**Issue by fqidz** [viperML/nh#165]
`sudo nixos-rebuild switch --flake /etc/nixos#default` works but `nh os switch /etc/nixos#default` doesn't work.

The nh command gives this error:
```
error: flake 'git+file:///etc/nixos' does not provide attribute 'packages.x86_64-linux.default#nixosConfigurations.""nixos"".config.system.build.toplevel', 'legacyPackages.x86_64-linux.default#nixosConfigurations.""nixos"".config.system.build.toplevel' or 'default#nixosConfigurations.""nixos"".config.system.build.toplevel'
┏━ 1 Errors:
┃ error: flake 'git+file:///etc/nixos' does not provide attribute 'packages.x86_64-linux.default#nixosConfigurations.""nixos"".config.system.build.toplevel', 'legacyPackages.x86_64-linu…
┣━━━
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 00:28:55 after 0s
Error:
   0: Command exited with status Exited(1)

```
which seems to be accessing the wrong 'path', as the nixos-rebuild command appears to be looking at this 'path' instead:
```
evaluating derivation 'git+file:///etc/nixos#nixosConfigurations."default".config.system.build.ni...
```

heres the relevant part from my `flake.nix` file, which works perfectly well with `nixos-rebuild`:
```
nixosConfigurations.default = nixpkgs.lib.nixosSystem {
  system = "x86_64-linux";
  specialArgs = {
    ...
  };
  modules = [
    ...
  ]
}
```

**Comment by viperML** [comment]
`nh os switch -H default /etc/nixos`

**Comment by polwex** [comment]
Why though? All flakes use the file#attribute syntax

**Comment by viperML** [comment]
> Why though? All flakes use the file#attribute syntax

Then it wouldn't make sense to use `/etc/nixos#default`, but rather `/etc/nixos#nixosConfigurations.default`, don't you think? `nixos-rebuild` goes out of its way to have a custom flake syntax, which I won't support in nh.

**Comment by cdo256** [comment]
I agree that we shouldn't use the confusing `nixos-rebuild` flake attributes. Since this is likely to a common pitfall, it might be worth adding a warning/error if the flake attribute doesn't start with `nixosConfiguraiton`:


```rust
                if attribute.is_empty() {
                    attribute.push(String::from("nixosConfigurations"));
                    attribute.push(hostname);
                } else if attribute.first() != Some(&String::from("nixosConfiguration")) {
                    warn!(
                        r#"
The provided flake attribute does not start with `nixosConfigurations`.
Note that flake references used by nh do not match the ones used in `nixos-rebuild`.
Instead you can pass the configuraiton name using the `-H` flag. Eg. use
    nh os switch /flake/dir -H my-host
instead of
    nh os switch /flake/dir#my-host
"#
                    )
                }

```

There's a fair amount of code duplication that would be worth addressing first, say by creating a `maybe_set_flake_default_value()` from `toplevel_for()`.

An adjacent issue is that `toplevel_for()` is shared between nixos.rs and darwin.rs, but the flake default is hardcoded to only work for nixos, with darwin.rs handling it in DarwinRebuildArgs. It makes sense to sort those out in the same PR if you think this is worth addressing?

**Comment by NotAShelf** [comment]
I have an open PR to address some of those concerns, at least partially. Feel free to leave a review or comments. I'll be back to nh probably next week.

**Comment by cdo256** [comment]
Ah perfect, should the PR be based on the `consolidate-logic` branch in that case? Otherwise the work would have to be repeated once that branch merges.

**Comment by NotAShelf** [comment]
Basing on my branch would be preferred, yes. I don't have further refactor plans (aside from fixing review comments) so if you plan to open a PR, it can be merged into mine before merging.
