### ISSUE TITLE
Feature Request: Support `doas` instead of strictly `sudo`

### ISSUE THREAD

**Issue by ModestTG** [viperML/nh#168]
I love this project. I currently am using `doas` instead of `sudo`, but I had to re-enable sudo in order for NH to work properly. I'm wondering if there is a way to use `doas` (or any other permission elevation tool) with this utility? The errors I got stated not to run the command as root and that permissions would be elevated internally. Let me know what you think!

**Comment by viperML** [comment]
duplicate #95
