### ISSUE TITLE
Question: Would you be happy to use a nix-uri parsing library?

### ISSUE THREAD

**Issue by Ben-PH** [viperML/nh#172]
[`nix-uri`](https://github.com/a-kenji/nix-uri/) was originally a spin-off project from [flake-edit](https://github.com/a-kenji/flake-edit). I decided to put some hours into nix-uri because I started running the resource-locator challenge in my [nixos-rebuild](https://github.com/Ben-PH/nixos-rsbuild/) rewrite.

I happened to come across this project just today, and I thought using a nix-specific resource locator might come in handy the same way it is intended for the projects I just mentioned

I'd be happy to take into account the needs and requirements of this project, if you see it as potentially useful. Here are some possible benefits it could bring:

- detailed resource-location destructuring before needing to dispatch `nix` commands.
- Useful error messages on malformed inputs
- more options with respect to what can easily be done with resource locators (in app editing, fall-back behavior, etc)

Keen to hear your thoughts

**Comment by viperML** [comment]
nh doesn't parse flake uri's, and I don't need to do that at the moment

**Comment by Ben-PH** [comment]
Righto. Is there any intent in the near future to validate/process the resource-location strings before dispatching the nix/other commands?

**Comment by viperML** [comment]
No
