### ISSUE TITLE
allow use of flake git ref?

### ISSUE THREAD

**Issue by Rafmaninoff** [viperML/nh#177]
Hello, I often forget to `git pull` before building, so, I was trying to make nh only build from github, like you can with `nixos-rebuild switch --flake github:user/repo`, however, programs.nh.flake must be of type path.

**Comment by viperML** [comment]
You can manually set the `FLAKE` environment variable in different ways, such as your shell config or environment.sessionVariables

**Comment by Shawn8901** [comment]
@Rafmaninoff  https://github.com/NixOS/nixpkgs/pull/358462 would address the request. The issue was not on nh side, but the nh module on nixpkgs. actually i was using it like viper suggests until i now tried to fully migrate to the nh module in nixpkgs.
