### ISSUE TITLE
DerivationReadError: hGetContents: Invalid argument (cannot decode byte sequence)

### ISSUE THREAD

**Issue by ModestTG** [viperML/nh#180]
I'm using nh and I'm getting the following errors when I run `doas nh os test -R -H <hostname> .` where the flake is in the current directory. When I do this I get the following errors:

```
nix-output-monitor error: DerivationReadError /nix/store/nqzjyb0dhw8rkk8m28s3gnhwg4hb4fjq-wheel-0.37.1-source.drv: hGetContents: invalid argument (cannot decode byte sequence starting from 195)
nix-output-monitor error: DerivationReadError /nix/store/s84006h94cd1b5s2dcplawvqhqzd8nd9-shadow-4.16.0.drv: hGetContents: invalid argument (cannot decode byte sequence starting from 226)
```

All various derivations and all byte sequence 195 or 226. I get several of these logs (~100 lines)

I run this command from a justfile but running the command manually doesn't seem to change the behavior.

Config:
from `flake.lock`

```json
    "nixpkgs": {
      "locked": {
        "lastModified": 1732014248,
        "narHash": "sha256-y/MEyuJ5oBWrWAic/14LaIr/u5E0wRVzyYsouYY3W6w=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "23e89b7da85c3640bbc2173fe04f4bd114342367",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },

```
nh version `3.6.0`

outpath: `/nix/store/v58s2hqyzpvbjyjx9k3680zzjbg1mb4x-nh-3.6.0`

installed via `environment.systemPackages = [ nh ];`

EDIT: Looks like it's related to this issue https://github.com/maralorn/nix-output-monitor/issues/136

**Comment by viperML** [comment]
Closing as it's a nom error
