### ISSUE TITLE
[Feature Request]: Add run0 (systemd-run) support in addition to sudo on Linux systems.

### ISSUE THREAD

**Issue by normalcea** [viperML/nh#185]
### Overview

[run0](https://www.freedesktop.org/software/systemd/man/devel/run0.html) is a new feature formally introduced in systemd v256 (NixOS 24.11+) that allows escalating privileges interactively similar to sudo.  Most notably, it isolates authentication from the terminal, instead using polkit among other benefits. 

### Scope 
run0 is mostly meant to be a drop-in replacement to sudo, so  `./src/commands.rs` as well as `./src/main.rs` would have to be modified to check whether or not run0 should be used in place of sudo.

The component determining that in my opinion should be an environment variable (i.e `NH_USE_RUN0` or something related) that is used on Linux systems. This could then be extended as an option within a Nix module ex: `useRun0 = true`

### Rationale
[Mastadon thread detailing run0](https://mastodon.social/@pid_eins/112353324518585654)

**Comment by viperML** [comment]
duplicate #95
