### ISSUE TITLE
`nh os switch` stopped working for me.

### ISSUE THREAD

**Issue by dkowis** [viperML/nh#197]
Forgive me if I'm doing things super wrongly, but it was working until I upgraded to 24.11.

```
nixboi@rockpro64 /e/nixos> sudo git pull
Already up to date.
nixboi@rockpro64 /e/nixos> nh os switch
> Building NixOS configuration
error:
       … while fetching the input 'git+file:///etc/nixos'

       error: opening Git repository '"/etc/nixos"': repository path '/etc/nixos' is not owned by current user
┏━ 1 Errors:
┃ error:
┃        … while fetching the input 'git+file:///etc/nixos'
┃
┃        error: opening Git repository '"/etc/nixos"': repository path '/etc/nixos' is not owned by current user
┣━━━
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 17:58:20 after 0s
Error:
   0: Command exited with status Exited(1)

Location:
   src/commands.rs:151
```

My `/etc/nixos` is owned by `root:root` and is pulled over http from my local forge instance. I was able to follow this pattern, which lets me use `nh` and also have configured the automatic updates, which seems to be working fine.

I am suspicious that I'm doing it wrong, but I don't know how not to do it wrong, and I couldn't quite see what things are.

My nixos configuration is here: https://forge.light.kow.is/kowis-projects/nixos-configuration

Thanks for any advice, and thanks for building a super cool project :D

**Comment by viperML** [comment]
nh calls nix as the current user, and that error is emitted by nix itself. The workflow I'd recommend is either having the repo owned by the same user as you call nh/nix, or calling nh as root with the "bypass root check" flag

**Comment by dkowis** [comment]
This brings up a different question a little outside of the scope of nh: 

How does one use `nh` to update a nixos host? /etc/nixos is supposed to be root:root right? 

`nixboi` user is in the nix admin list in `/etc/nix/nix.conf`, so it should have permission to do nix things. Should I instead have the flake repo cloned into that user's home dir?

I couldn't find this written somewhere, either by googling for the wrong things, or just not looking in the right places.

**Comment by viperML** [comment]
`nix.conf` only allows to add extra trusted users, that can load binaries into the nix store by their own, nothing more. The activation script (what nixos-rebuild and nh run) is a regular script that must be run as root, and managing a git repo is completely out of scope.

> /etc/nixos is supposed to be root:root right?

No. As I mentioned, you may choose to call nh as root or use a repo owned by your user.

**Comment by dkowis** [comment]
Thanks for indulging my questions :D
