### ISSUE TITLE
Run `nix build` as root/via sudo if the flake path is in the nix store

### ISSUE THREAD

**Issue by uku3lig** [viperML/nh#200]
This issue is (partly) related to #197 and NixOS/nix#10202.

My current workflow for deploying a configuration to a remote machine is the following:
- Copy the flake source to the remote machine via `nix copy`, which adds it to the nix store
- Run `sudo nixos-rebuild switch --flake /nix/store/...-source#hostname` to switch

Since `nixos-rebuild` is run as root via sudo, it has no problem using the store path since it's also owned by root. However, when trying to replace `nixos-rebuild` with nh in this workflow, since nh (and therefore `nix build`) is meant to be run as an unprivileged user, I get the `repository path ... is not owned by current user` error.

One workaround is to run nh with sudo and `--bypass-root-check`, but the mere existence of this check makes me assume that it isn't recommended. Therefore, another solution could be to run `nix build` in nh as root/via sudo, to fix this permission check; or to wait for upstream to fix the issue.

**Comment by viperML** [comment]
Tbh using `nix copy` just to copy the flake source is kinda cursed, just use scp at that point.

Or rathee, build locally, push the resulting closure and activate the closure with `nh os switch /nix/store/path-to-toplevel`

**Comment by uku3lig** [comment]
> Tbh using `nix copy` just to copy the flake source is kinda cursed, just use scp at that point.

Yeah, I suppose scp in a temporary directory could work, but it does feel like some kind of dirty hack... :/ Plus, the source would end up being copied to the nix store anyway.

*Also, as a side note, all of [nixinate](https://github.com/MatthewCroughan/nixinate/blob/452f33c60df5b72ad0858f5f2cf224bdf1f17746/flake.nix#L54), [deploy-rs](https://github.com/serokell/deploy-rs/blob/aa07eb05537d4cd025e2310397a6adcedfe72c76/src/push.rs#L171-L180) and [nixos-rebuild itself](https://github.com/NixOS/nixpkgs/blob/e5a7bfa36e9350bd3ed6eaf95866ebc96dae82c5/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L269-L281) use nix copy (or nix-copy-closure in the case of nixos-rebuild), so maybe it's not as cursed as it sounds!*

> Or rathee, build locally, push the resulting closure and activate the closure with `nh os switch /nix/store/path-to-toplevel`

I would ideally want to avoid this. The machines I want to deploy to have more processing power and a much better bandwidth, which makes them a much better candidate to be the build host.

**Comment by viperML** [comment]
I don't have the bandwidth to turn nh into a deployment tool, so I'll close this for now.
