### ISSUE TITLE
missing .local/state/nix/profiles

### ISSUE THREAD

**Issue by StarrFox** [viperML/nh#23]
hello, I don't have a `~/.local/state/nix/profiles` folder and this prevents me from using `nh clean all/user`; I believe this is some feature from a newer nix version? I'm using the latest stable version of nixos `23.05` with nix version `2.13.3`

maybe we could have a flag to ignore this folder or it could even do it by default and print a warning or something

I tested that this was the issue by removing it in a fork <https://github.com/viperML/nh/compare/master...StarrFox:nh:master>

**Comment by viperML** [comment]
Yeah I wrote that before knowing nix actually uses NIX_PROFILES. Could you post the output for `printenv NIX_PROFILES` and `sudo printenv NIX_PROFILES` ?

**Comment by StarrFox** [comment]
❯ printenv NIX_PROFILES
/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/starr /home/starr/.nix-profile /var/lib/flatpak/exports /home/starr/.local/share/flatpak/exports

❯ sudo printenv NIX_PROFILES
[no output]

**Comment by viperML** [comment]
if you are able to implement such that `nh clean user` reads NIX_PROFILES to know which profiles to link, you can do a PR.

Otherwise I'll be busy this month and won't be able to implement it

**Comment by StarrFox** [comment]
I ran into a few issues trying to use NIX_PROFILES
- it uses a space for separation so I don't really know how to handle paths that have spaces in them
- I don't know what to do with the non-profile looking stuff in NIX_PROFILES like /var/lib/flatpak/exports which for me just has a `bin` and `share`
- some of the paths don't actually exist; for example I have `/home/starr/.local/share/flatpak/exports` in NIX_PROFILES but that path doesn't actually exist

**Comment by viperML** [comment]
Is this question in regards to commit https://github.com/viperML/nh/commit/8b2890f3eb9d5618e2e9cb45dd95d0df65b89e30 ?

That one should work for `nh clean user`

About the questions:

- That is right, and probably should be reported to upstream. From my part, I would say it is sensible to not support paths with spaces 🤷 
- 2 & 3: The reader should automatically try to parse the paths as profile names. If they are not detected as profile/generation names, the entry is just ignored.

As for`nh clean all`, this one is going to be tricky. NIX_PROFILES is a user-specific environment variable, and can't be used to detect all the profiles for all users.

**Comment by viperML** [comment]
Is this issue still relevant? @StarrFox

**Comment by StarrFox** [comment]
the stable nixos channel is using the nix with this now so it's probably alright to close
