### ISSUE TITLE
missing /nix/var/nix/profiles/per-user/{}/home-manager

### ISSUE THREAD

**Issue by StarrFox** [viperML/nh#32]
on my system I no longer have the `/nix/var/nix/profiles/per-user/starr/home-manager` path so when running `nh home switch` I just get a message that the path is missing when comparing changes

I do have `/nix/var/nix/profiles/per-user/starr/profile` and I tried that in a fork to see if it was the fix https://github.com/StarrFox/nh/commit/d74a227b7ffd52c2f2f82e1d3026e4d6440b78b2 but the output seems to mention a lot of stuff that didnt really change now

**Comment by viperML** [comment]
Could you bisect HM to know the breaking commit?

**Comment by StarrFox** [comment]
I tried looking at their commit history to figure out when the change happened but I couldnt find it

**Comment by StarrFox** [comment]
I'm using the release-23.05 branch https://github.com/StarrFox/systems/blob/ab2db773fbe772315cd32e961d265d760b148fca/flake.nix#L25

**Comment by viperML** [comment]
https://git-scm.com/docs/git-bisect

**Comment by StarrFox** [comment]
I'm pretty sure it's this commit https://github.com/nix-community/home-manager/commit/93f5cb2482dd20e57eb8ca6c819cdad9738f98a0
