### ISSUE TITLE
setup issue: flake input attribute 'nh' is a thunk while a string, Boolean, or integer is expected

### ISSUE THREAD

**Issue by novoid** [viperML/nh#33]
Hi,

Disclaimer: [NixOS beginner here](https://www.karl-voit.at/2023/09/12/nix/), don't exclude stupidity on my side.

Your tool sounds like a nice option for me to handle my flakes setup mostly because of the diff and ask option. However, I wasn't able to set it up correctly so far. My modifications are: https://github.com/novoid/nixos-config/commit/5da41d8d55a184f02d707c31705f9149b90fc766

`sudo nixos-rebuild switch --flake /home/vk/nixos` results in:

```
warning: Git tree '/home/vk/nixos' is dirty
error: flake input attribute 'nh' is a thunk while a string, Boolean, or integer is expected
(use '--show-trace' to show detailed location information)
```

I'm pretty sure that at least "\<system\>" should be replaced by $HOSTNAME (although I don't understand why yet) but that doesn't change the error message. So I suspect the error already in the input definition which I copied 1:1 from the README.

Maybe you've got other people who are unexperienced enough to make the same mistake I made?

**Comment by novoid** [comment]
Oh damn, too early.

```
error: builder for '/nix/store/wp4ibyfwfx9andky0pb5hkqff3nsj7q2-nh-3.4.6.drv' failed with exit code 101;
       last 10 log lines:
       > Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
       > Finished cargoSetupPostPatchHook
       > configuring
       > building
       > Executing cargoBuildHook
       > ++ env CC_x86_64-unknown-linux-gnu=/nix/store/lcf37pgp3rgww67v9x2990hbfwx96c1w-gcc-wrapper-12.2.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/lcf37pgp3rgww67v9x2990hbfwx96c1w-gcc-wrapper-12.2.0/bin/c++ CC_x86_64-unknown-linux-gnu=/nix/store/lcf37pgp3rgww67v9x2990hbfwx96c1w-gcc-wrapper-12.2.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/lcf37pgp3rgww67v9x2990hbfwx96c1w-gcc-wrapper-12.2.0/bin/c++ cargo build -j 8 --target x86_64-unknown-linux-gnu --frozen --release
       > error: package `clap_lex v0.5.1` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
       > Either upgrade to rustc 1.70.0 or newer, or use
       > cargo update -p clap_lex@0.5.1 --precise ver
       > where `ver` is the latest version of `clap_lex` supporting rustc 1.69.0
       For full logs, run 'nix log /nix/store/wp4ibyfwfx9andky0pb5hkqff3nsj7q2-nh-3.4.6.drv'.
error: 1 dependencies of derivation '/nix/store/ajk4diin39zrcyzdy036d8nnfd9ky7n9-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cqczjbkvfmpqyniwid352q6vh8xcg8i4-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7231kyx3gq72566cmp3fcz6r2gv7ms6m-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/w82x56lkvqbhj6wwj10cpvlr1a0cskzr-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/61n7s1kn21xx6w2v8s4m5a5gac2nciv6-nixos-system-rise-23.05.20230907.4f77ea6.drv' failed to build
```

I thought that Nix is fetching the appropriate dependencies by itself ...

Does this refer to `inputs.nixpkgs.follows = "nixpkgs";`?

**Comment by viperML** [comment]
Yeah, I update nh' deps by building it againsr nixos-unstable. 

Apparently an update for one of the deps is not compatible with the rustc included in nixos-23.05

While the quick fix is to remove the follows, I should follow the sable Nixos release

**Comment by novoid** [comment]
Yes, removing the follows-statement works for now (fetching another 2GB from the Internet :astonished: ).

**Comment by viperML** [comment]
Nevermind, I thought `cargo update` would somehow consider the minimum rust version for all the dependencies. So I will keep using nixos-unstable for now.

> (fetching another 2GB from the Internet 😲 )
Those are build-time dependencies, which can be garbage collected. The actual program along its deps (nvd, nom) is smaller:

```
$ nix path-info -Sh ./result
/nix/store/rw2vvlwjqq6har93h3iwn9z0vd2gi8j4-nh-3.4.6     164.6M
```

**Comment by nouritsu** [comment]
> I added a comment on your repo

@viperML Is it possible for you to link your comments or perhaps explain the fix in the issue so it is easily found by other users? Currently, this thread cannot be used as documentation.

This is one of the few pages that appear when you search "flake input attribute 'swww' is a thunk". Other somewhat useful pages include: [NixOS Discourse](https://discourse.nixos.org/t/thunk-error-when-enabling-snapd-on-flake/49737) and [Reddit](https://www.reddit.com/r/NixOS/comments/1delm85/flakenix_errors_with_expected_a_set_but_got_a/). The latter being unrelated for errors listed in this thread.

**Comment by viperML** [comment]
No, I cannot.
