### ISSUE TITLE
blue foreground on black background can't be read

### ISSUE THREAD

**Issue by novoid** [viperML/nh#36]
Hi,

I'm having a white on black terminal [setup](https://github.com/novoid/nixos-config).

As you can see in the screenshot, blue text is not readable:

![2023-09-17T17 13 54 nh with blue foreground on black background -- screenshots](https://github.com/viperML/nh/assets/727493/3e62a073-c670-4a84-a492-b0383d9e263c)

Maybe you can think of a solution here?

**Comment by viperML** [comment]
What you are seeing is the output of NOM : https://github.com/maralorn/nix-output-monitor

Reopen the issue there 👍

**Comment by novoid** [comment]
Sure, thank you!
