### ISSUE TITLE
Fix `nh os <something> --update`

### ISSUE THREAD

**Issue by viperML** [viperML/nh#46]
https://github.com/viperML/nh/blob/375c6cf57de3a839b7937358659bea526da27eae/src/nixos.rs#L54

Nix 2.19 changes the syntax

**Comment by eclairevoyant** [comment]
context: https://github.com/NixOS/nix/blob/master/src/nix/flake-update.md

`nix flake update (arg)` now updates the flake input named (arg); updating a flakeref requires `--flake (flakeref)`

**Comment by eclairevoyant** [comment]
#75 fixes this?

**Comment by NotAShelf** [comment]
'puter... my worst enemy...
