### ISSUE TITLE
Flake ref cannot be a symlink

### ISSUE THREAD

**Issue by terlar** [viperML/nh#57]
Not sure if this is desired, but it might be nice to be able to support a symlinked flake path, I discovered that when I tried to switch to my symlinked `/etc/nixos`.

```
$ nh os switch /etc/nixos

> Building NixOS configuration
error: path '/etc/nixos' is not a flake (because it's not a directory)
┏━ 1 Errors:
┃ error: path '/etc/nixos' is not a flake (because it's not a directory)
┣━━━
┗━ ∑ ⚠ Exited with 1 errors reported by nix at 10:30:31 after 0s
Error:
   0: Building NixOS configuration
   1: Command exited with status Exited(1)
```

**Comment by viperML** [comment]
That error is being thrown by nix

**Comment by viperML** [comment]
https://github.com/NixOS/nix/issues/8013

**Comment by terlar** [comment]
Interesting, because if you rely on the default behavior of `nixos-rebuild`, e.g. don't specify an explicit `--flake`. It will detect that there is a `flake.nix` inside `/etc/nixos` and work in that way. I created a separate ticket for that: #58

So if you don't specify `--flake`, but do have a flake within `/etc/nixos` then it will work with a symlinked flake repo.
