### ISSUE TITLE
`nh clean all` tries to clean nonexistent directories

### ISSUE THREAD

**Issue by NotAShelf** [viperML/nh#62]
Starting from commit fc80c10dde226fa809690855f11eae72ef5d4df9 (according to a bisect), `nh clean all` parses `/root/.local/state` and `/var/empty/.local/state` which are empty while using nix version `2.20.0pre20231207_661b025`.

Relevant logs:
```
! Failed to read profiles directory dir="/root/.local/state/nix/profiles" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
! Failed to read profiles directory dir="/var/empty/.local/state/nix/profiles" error=Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by viperML** [comment]
That is correct. I have no way of knowing if that is desired behaviour or not, so I decides to just show the warning that you can ignore.

/var/empty comes from the nobody user (because it is a regular user with uid>1000)

**Comment by NotAShelf** [comment]
I understand the thought process, I think. But the error messages repeat around 35 times (I'm pretty sure the number is prone to change) and tends to be a little more than something you can ignore - maybe a flag to ignore those warnings? Or maybe check if those directories exist/are full and bail *very* early if they are to avoid seeing that many error messages?

**Comment by viperML** [comment]
Could you run nh with --verbose and post the log with those 35 repetitions?

**Comment by NotAShelf** [comment]
Sorry for the delay, I was outside.

https://p.frzn.dev/hzi should have everything.

**Comment by viperML** [comment]
Ah, as you can see it's because of the nixbld users, they should be filtered.

I'm busy this week, but I'll fix it soon

**Comment by viperML** [comment]
Another option is to just scan users with an arbitrary low UID, for example 1000 to 1100. (To distinguish between real user managed, with pontetial profiles to be cleaned, and system users)
