### ISSUE TITLE
Module warnings (trace)

### ISSUE THREAD

**Issue by Lillecarl** [viperML/nh#64]
Hi!

I've noticed that when using nh I miss deprecations and such in modules as they're never printed visibly to the console. Am i holding it wrong or is this an oversight? 😄 

It'd be cool if they were printed at the end so users are aware that their configuration is deprecated and should be fixed.

**Comment by viperML** [comment]
I've known this issue, but forgot to open a ticker here in github, thanks.

This is the affected code: https://github.com/viperML/nh/blob/36eba281576afe0f67e5aafb4e7a414f256dba31/src/commands.rs#L122-L137

(I don't have a stable internet connection this week, so I'll look into it)

**Comment by Lillecarl** [comment]
@viperML How about an option building the output again without nom, and/or made cancelable?

**Comment by viperML** [comment]
You can already build without nom, though the interface is quite bad.

https://github.com/viperML/nh/blob/6947e6f6f234d303131ecc1e54ef6703c82257e3/src/interface.rs#L133-L139

https://github.com/viperML/nh/blob/6947e6f6f234d303131ecc1e54ef6703c82257e3/package.nix#L54

**Comment by viperML** [comment]
https://github.com/viperML/nh/commit/3f148b0c7f2d56be65dc55628f6b2e68ee10e231

**Comment by Lillecarl** [comment]
@viperML I implemented something resembling nh, but in fish-shell and very shitty. I pipe through tee then parse the output once more with shell scripts to get messages starting with "trace:".

```
    nix \
        build \
        $fullflake \
        --out-link $result \
        --log-format internal-json -v &| tee oslog.json &| nom --json || begin
        echo "Failed to build $fullflake"
        return 1
    end

    for line in (cat oslog.json | rg "trace:.*")
        set jmsg (echo $line | sed "s/@nix //")
        set tmsg (echo $jmsg | jq -r ".msg")
        printf $tmsg
    end
```

It's not pretty, but it works!

**Comment by viperML** [comment]
There's a fix for nom in the issue linked https://github.com/maralorn/nix-output-monitor/issues/128

**Comment by Lillecarl** [comment]
Crazy timing! Thanks for the info and your work! 😄
