### ISSUE TITLE
nh darwin: implement

### ISSUE THREAD

**Issue by Guanran928** [viperML/nh#67]
`nh os switch` currently does not work for `nix-darwin`.

![image](https://github.com/viperML/nh/assets/68757440/e04137c3-6659-450c-a59e-11754e7d03b8)

**Comment by viperML** [comment]
`nh os` is a nixos-rebuild rewrite, doesn't have anything to do with nix-darwin

**Comment by SolidRhino** [comment]
This would be a great addition!

**Comment by viperML** [comment]
I don't use macos, so I don't think I'll ever implement this

**Comment by ToyVo** [comment]
I heard about this project a couple days ago, and I decided to take a shot at updating for darwin, I'll make a PR once I'm done for comment, but for reference I'm looking at the darwin-rebuild command https://github.com/LnL7/nix-darwin/blob/master/pkgs/nix-tools/darwin-rebuild.sh

[This line](https://github.com/viperML/nh/blob/master/src/nixos.rs#L46) that builds _flake_#nixosConfiguration._hostname_.config.system.build.toplevel needs to be switched to _flake_#darwinConfiguration._hostname_.config.system.build.toplevel

Then [this line](https://github.com/viperML/nh/blob/master/src/nixos.rs#L156) that runs switch-to-configuration, that script doesn't exist on darwin but darwin rebuild runs activate-user then activate within it's result directory
