### ISSUE TITLE
Add SPECIALISATION env 

### ISSUE THREAD

**Issue by emanueljg** [viperML/nh#77]
Just as how you want a default FLAKE, it's also useful to have a default specialisation so you don't have to pass it every time.

**Comment by viperML** [comment]
You forgot to configure this https://github.com/viperML/nh?tab=readme-ov-file#configure-specialisations

**Comment by emanueljg** [comment]
> You forgot to configure this https://github.com/viperML/nh?tab=readme-ov-file#configure-specialisations

Right, it's just a lot more ergonomical to have that default spec in an env var.

**Comment by viperML** [comment]
If you switch from one specialisation to other, new env vars don't propagate to the active session, while a change to a file on /etc does

**Comment by emanueljg** [comment]
> If you switch from one specialisation to other, new env vars don't propagate to the active session, while a change to a file on /etc does

Alright, fair enough.
