### ISSUE TITLE
Permission denied when trying to update flake.lock 

### ISSUE THREAD

**Issue by Yucklys** [viperML/nh#79]
I put my flake.nix under `/etc/nixos`, as this is where the `sudo nixos-rebuild switch` default to. However, when I try to update the flake inputs by `nh os switch --update`, it successfully pulls the updates, but failed to update the flake.lock file due to permission denied. I have to manually update the flake inputs before I run this command. I think nh should ask for sudo permission to update the lock, as `/etc/nixos/flake.nix` is a common place that people will store their flake files.
![image](https://github.com/viperML/nh/assets/34306920/490f0134-e26e-41a5-ab56-f857cc478b36)

**Comment by viperML** [comment]
nh doesn't run nix as root, only the activation scripts

**Comment by Yucklys** [comment]
I just want to know if this is the intended behavior, as it requires another command to upgrade. I write a wrapper for the commands and now it work perfectly.

**Comment by painsucker2** [comment]
![Screenshot_20240419_125001](https://github.com/viperML/nh/assets/157894292/6f0c31ce-3d59-4a1c-a7eb-62d8fc7334bc)
Same issue.

**Comment by painsucker2** [comment]
zsssssssss





















s

> nh doesn't run nix as root, only the activation scripts

I'm guessing that's the issue, as flakes are updated by the nix command?
I'm not that experienced in nix, so excuse me if I'm wrong.

**Comment by viperML** [comment]
I know the issue but not the cleanest way to handle it

**Comment by painsucker2** [comment]
So the temporary fix is changing the ownership of flake.nix and flake.lock?

**Comment by Different-Name** [comment]
I am also struggling with this, nh os switch whenever I update my flake inputs, shouldn't nh ask for sudo like it does at other times it is required?

**Comment by viperML** [comment]
No, because I want to keep the evaluation apart from root

**Comment by Different-Name** [comment]
Do you suggest permanently changing ownership then?

**Comment by viperML** [comment]
Running nix flake update as the same user that owns the flake

**Comment by gepbird** [comment]
I have a similar issue: using agenix the quick and dirty way and putting a `builtins.readFile config.age.secrets.foo.path` in the config, I get a permission error: *error: opening file '/run/agenix/foo': Permission denied*

And `sudo -E nh os switch` doesn't work: *Don't run nh os as root. I will call sudo internally as needed*. Whats the reason for this sudo check?

**Comment by viperML** [comment]
Well `readFile secret` is certainly a usecase I want to block, so nh was working as intended.

**Comment by darshmashru** [comment]
Maybe try this? Worked for me.
```bash
 sudo chown <user_name> ../flake.lock 
```

**Comment by Yucklys** [comment]
> Maybe try this? Worked for me.
> 
> ```shell
>  sudo chown <user_name> ../flake.lock 
> ```

Change ownership did let nh to access flake, but it didn't use cachix stores correctly. I suppose it is because it is using the cachix setting in the user directory.

**Comment by Kruziikrel13** [comment]
@Yucklys What was the issue with your Cachix setup?

**Comment by Tealk** [comment]
I also just stumbled across this problem on nixos. Files in /etc always have root permissions, including /etc/nixos/flake.lock why does switch use sudo, but the --update doesn't?

**Comment by NotAShelf** [comment]
The important distinction between switch and `nix flake update` is that switch **cannot** run without escalation. THe `switch-to-configuration` binary expects privileges to be able to switch your system, whereas `nix flake update` *could* run without escalation if your flake is in your `$HOME` or if you `chown` your configuration dir. We'll change this to an ask-to-escalate.
