### ISSUE TITLE
Add searching in home manager options

### ISSUE THREAD

**Issue by Eddio0141** [viperML/nh#86]
Currently I use [this 3rd party site](https://home-manager-options.extranix.com/), but would be great to have on the shell instead in a similar fashion to `nh search`

**Comment by tym2k1** [comment]
You can use man home-configuration.nix to list all available configuration options, ensuring they are up-to-date with your home-manager version. Personally, I think implementing the feature you're proposing might introduce unnecessary overhead. However, if it were to be implemented, starting with the existing manual pages could be a good approach

**Comment by viperML** [comment]
I don"t plan to write any HM features myself
