### ISSUE TITLE
implement `nh home --backup`

### ISSUE THREAD

**Issue by HirschBerge** [viperML/nh#87]
Hello, I think it would be great to have a version of `home-manager -b backup` for nh.

Relevant line from HM.
```
  -b EXT            Move existing files to new path rather than fail.
```

Thank you!

**Comment by viperML** [comment]
I believe this is implemented upstream by just exporting an env var https://github.com/nix-community/home-manager/blob/f46814ec7cbef9c2aef18ca1cbe89f2bb1e8c394/home-manager/home-manager#L962C20-L962C43

I'll look into it

**Comment by HirschBerge** [comment]
I have added the var in question to my sessionVariables and will test.

**Comment by HirschBerge** [comment]
This worked.
I am content to close as this is actually a better solution than I was asking for.
