### ISSUE TITLE
What are "specialisations"?

### ISSUE THREAD

**Issue by TornaxO7** [viperML/nh#94]
The readme says, that I can create some [specialisations](https://github.com/viperML/nh?tab=readme-ov-file#specialisations-support) but what are those? What is meant with `configuration` in `specialisation."foo".configuration`? Am I only able to define environment variables in it or is it meant to be used as if it would be my `/etc/nixos/configuration.nix`?

**Comment by thenbe** [comment]
See https://wiki.nixos.org/wiki/Specialisation

**Comment by TornaxO7** [comment]
> See https://wiki.nixos.org/wiki/Specialisation

Oooh, thank you!
