### ISSUE TITLE
Don't fail when root

### ISSUE THREAD

**Issue by PaulGrandperrin** [viperML/nh#95]
I often use root to perform many administrative operations instead of prefixing all my commands with "sudo".
Even more so when updating my flake as my `/etc/nixos` is only allowed to root.

I know that `nh` blocking my way of working comes from a good intention but I really do know what I'm doing :D 
I mean, why not printing a warning like some others tools do, but plain blocking is really harsh..

Please consider :pray: 

Also, `nixos-rebuild` doesn't force using non-root too

**Comment by viperML** [comment]
Running nix as root does have some consequences, such as skipping the eval cache, and maybe more importantly the daemon. I'd rather not at this point of friction, and this was a design decision from the very beginning.

>  as my /etc/nixos is only allowed to root
Personally I keep my $FLAKE in ~/Documents

**Comment by PaulGrandperrin** [comment]
I didn't double-check, but I'm pretty sure using root neither skips the eval cache nor the daemon.

What friction would be added by removing the denial?

**Comment by PaulGrandperrin** [comment]
I guess you got my point that I don't think that it's `nh`'s role/responsibility to decide how users should use their computer to elevate privileges, so I don't want to be more annoying with you.

I'll keep my flake in "/etc/nixos" since it's the standard location where many other tools expect it to be, and it's part of how I keep a healthy security separation between my user and root.

I'll just patch my `nh` locally since it's so easy with Nix (I'm still high on Nix awesomeness ;) )

**Comment by PaulGrandperrin** [comment]
I checked about using the daemon and eval caching and it seems you're right!
I never noticed any difference, but I guess it should in theory be faster when using non-root, right?

I guess I won't patch `nh` and just create a wrapper that `sudo`'s as some non-root user before launching `nh` itself then. Problem solved!

**Comment by viperML** [comment]
> in theory be faster when using non-root, right?

It's just that /root/.cache and $HOME/.cache is not shared, so you may get duplicate cache hits.

**Comment by PaulGrandperrin** [comment]
I'd love to learn more about that. 

So the nix tools don't have the correct behavior when run as root, why is that? 

I can't easily find documentation on why they choose to behave in an inferior way when they could work the same way as when non-root.

**Comment by PaulGrandperrin** [comment]
ahhh I understood what you meant! Sorry I just woke up...

So there's no problem with Nix, it's just that my user and root won't share their respective cache, right?

So, in my use case, I should actually reverse your check, to only allow running `nh` as root, to prevent me from running it as my user by mistake.

I want to always be already root when I update my OS and I don't want an unprivileged user to be able to compromise the nix cache used to rebuild the OS.

**Comment by crabdancing** [comment]
I'd like to second making it possible to use `nh` as root. It seems like an unnecessary imposition, especially since the mainline workflow (`/etc/nixos`) so heavily leans in that direction. If we've confirmed that the cache does in fact work (which matches my understanding too), then what is the reason for keeping this restriction?

**Comment by viperML** [comment]
The eval cache is not shared between root and your users, and I want to only use my user's eval cache.

**Comment by crabdancing** [comment]
@viperML 

It's still possible to have cache misses if you log in as another user, though.

Would you be willing to accept a PR that lets you globally force a specific user via an environment variable as an alternative?

**Comment by PaulGrandperrin** [comment]
> I'd like to second making it possible to use `nh` as root. It seems like an unnecessary imposition, especially since the mainline workflow (`/etc/nixos`) so heavily leans in that direction. If we've confirmed that the cache does in fact work (which matches my understanding too), then what is the reason for keeping this restriction?

You can use the solution I provided, it's a little annoying that it recompiles every now and then, but it's simple and works perfectly. I never had issues!

My workflow is also based on using root for root related tasks and not giving password-less sudo to my main user.

I still don't understand the idea that `nh` should call `sudo` itself when everyone is used to doing `sudo myAdminTool`. And paternalistically forcing it artificially by blocking the other method.

Anyway, it's a great tool and it's open source so i'm very thankful!

**Comment by PaulGrandperrin** [comment]
Also importantly, it's probably a security issue that the original `nh` uses the user cache.

I didn't check, but that probably means that it could be used for privilege escalation even if sudo is password protected.

Of course for the user to be protected in the first place, it would need to source its prompt from user read-only files in the first place..

**Comment by viperML** [comment]
I also want to add that the environment variables for a `nix build` process can affect some of the outcome, namely NIX_CONFIG, the flake registry, ssh configuration for private flakes, etc. And I am not sure that sudo will keep the same env variables, and the user can set some weird sudo config (or doas wrappers....).

Ideally I would move the check into somwhere in the refactor from #107, but I need to actually put into code what I want there...

I will write a bypass in the meantime.

**Comment by crabdancing** [comment]
@viperML Oh! You can pretty easily declaratively configure `sudo` to retain environment variables, if you want. E.g., if you want to make GUI applications work with sudo, you could do:

```nix
security.sudo-rs.extraConfig = ''
  Defaults env_keep += "DISPLAY XAUTHORITY WAYLAND_DISPLAY"
'';
```

**Comment by PaulGrandperrin** [comment]
@viperML oh mais t'es grenoblois ! Incroyable, le gars qui maintient nixvim aussi, il doit être a l'INRIA aussi je crois!

**Comment by PaulGrandperrin** [comment]
Ah oui, je viens de voir que @GaetanLepage est aussi a l'INRIA, vous devez vous connaître alors!

Je suis a Meylan, vous faites des événements en rapport avec Nix/NixOS ? Ca serait cool de rencontrer des Nixers!

**Comment by PaulGrandperrin** [comment]
> @viperML 
> 
> Edit: If the concern is that people might try to directly `sudo nh` and then the flag would be gone from the environment, one option is:
> 
> ```nix
> security.sudo.extraConfig = ''
>   Defaults env_keep += "NH_REQURE_ROOT"
> '';
> ```
> 
> This feels more like a workaround though. Could require a module to be added. Alternatively, we could do parsing?

Maybe it's not an issue, people who want `nh` to source its envvars from root will use `sudo nh` and people who want them from their user session will use `nh` directly, which will use `sudo/sudo-rs/please/doas` internally.

**Comment by viperML** [comment]
Initially I was thinking about a `NH_ROOT_CHECK_BYPASS` env var, but it won't be propagated by sudo by default, so I added `-R`. I don't want to commit directly to master, to hear second opinions. https://github.com/viperML/nh/compare/master...root-bypass

I'm also not sure if this will be the final API after #107 ...

**Comment by viperML** [comment]
> Je suis a Meylan, vous faites des événements en rapport avec Nix/NixOS ? Ca serait cool de rencontrer des Nixers!

@PaulGrandperrin I know some people did Nix in my office before me, so maybe it was him. Maybe you guys want to keep the conversation in a private space ^^

**Comment by PaulGrandperrin** [comment]
> Initially I was thinking about a `NH_ROOT_CHECK_BYPASS` env var, but it won't be propagated by sudo by default, so I added `-R`. I don't want to commit directly to master, to hear second opinions. https://github.com/viperML/nh/compare/master...root-bypass

This seems perfectly fine, I would put `NH_ROOT_CHECK_BYPASS` in my root environment, not in my user environment. So whether I call `nh` from root directly or from `sudo`, it'll work.

Passing `-R` all the time would be much more annoying.

> 
> I'm also not sure if this will be the final API after #107 ...

**Comment by PaulGrandperrin** [comment]
`sudo env` correctly shows the envvars from my `environment.sessionVariables`

**Comment by crabdancing** [comment]
@PaulGrandperrin Looks like it finally broke:

```
error: builder for '/nix/store/8vkxdpcwwdsx7v6181mdv814j54g28i8-nh-3.5.26.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/p28zmja7mgzjhrrz7jpz3j0bss56hsj8-source
       > source root is source
       > Executing cargoSetupPostUnpackHook
       > unpacking source archive /nix/store/x3y55av3mchq70i08fzjaqd8a0ijlika-nh-3.5.26-vendor.tar.gz
       > Finished cargoSetupPostUnpackHook
       > Running phase: patchPhase
       > applying patch /nix/store/mzs0y6adgh81ch5cd1f879c3kzsm41iv-bea0ce26e4b1a260e285164c49456d70d346c924.patch
       > patching file src/nixos.rs
       > Hunk #1 FAILED at 27.
       > 1 out of 1 hunk FAILED -- saving rejects to file src/nixos.rs.rej
       For full logs, run 'nix log /nix/store/8vkxdpcwwdsx7v6181mdv814j54g28i8-nh-3.5.26.drv'.
```

Good thing we got this upstreamed. :P

**Comment by PaulGrandperrin** [comment]
When I saw @viperML implemented the override, I immediately moved to the new version: https://github.com/PaulGrandperrin/nix-systems/commit/11ac608d1b8637ba7929a3a73dadec9a75703781

My laptop is quite slow, so I'm glad I don't have to locally compile `nh` anymore!

Anyway, it was really cool to be able to have an out-of-tree patch be applied automatically thanks to NixOS!
