### ISSUE TITLE
nh errors out when a root only older is present in /etc/nixos

### ISSUE THREAD

**Issue by afarinetti** [viperML/nh#96]
When you have a root:root 700 folder in `/etc/nixos` (e.g. `/etc/nixos/secrets`) NH will error out that it cannot access the folder.

**Comment by viperML** [comment]
duplicate #95

**Comment by viperML** [comment]
In this case, nh saved you from copying your very secret /etc/nixos to the /nix/store, world readable as 555

**Comment by viperML** [comment]
Could you link me these wiki articles?

**Comment by afarinetti** [comment]
The particular example I was looking at:
- https://nixos.wiki/wiki/Agenix

Though, this gives disagreeing info:
- https://nixos.wiki/wiki/Comparison_of_secret_managing_schemes

I don't care either way where it goes in `/etc/nixos`, I was just trying to follow examples 🤣

**Comment by viperML** [comment]
Ah right, what that wiki article describes is storing the encrypted secret in /etc/nixos/secrets. As you use flakes, the encrypted secrets will be leaked into the /nix/store, even if you use 700. This is known, and for example my server's encrypted secrets are publicly availabe here: <https://github.com/viperML/neoinfra/tree/master/secrets>.

Also the wiki has been recently moved into an official domain: https://wiki.nixos.org/wiki/Agenix

**Comment by afarinetti** [comment]
Thank you for the explanation! I'm still really new to Nix!
